# Generated by Django 4.0 on 2023-01-29 06:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=250)),
                ('miqdori', models.PositiveIntegerField()),
                ('miqdor_birligi', models.CharField(help_text="O'lchov birligini kiriting: Kg, Tonna, Vagon, Litr, Dona", max_length=150, null=True)),
                ('birlik_narxi', models.FloatField(null=True)),
                ('sotiladigan_narxi', models.FloatField(null=True)),
                ('tavsif', models.TextField()),
                ('photo', models.ImageField(default='images/no-image.jpg', upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoldProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdori', models.PositiveIntegerField(help_text='Sotilgan mahsulot miqdorini kiriting.', null=True)),
                ('sold_product_price', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldproducts', to='products.allproducts')),
            ],
        ),
    ]
