# Generated by Django 4.0 on 2023-01-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproducts',
            name='sold_product_price',
            field=models.FloatField(default=0),
        ),
    ]
