# Generated by Django 4.0 on 2023-01-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproducts',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
