# Generated by Django 4.0 on 2023-01-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_soldproducts_sold_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproducts',
            name='sotiladigan_narxi',
            field=models.FloatField(null=True),
        ),
    ]
