# Generated by Django 4.0 on 2023-01-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_allproducts_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproducts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
