# Generated by Django 4.0 on 2023-01-18 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_allproducts_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allproducts',
            name='user',
        ),
    ]
