# Generated by Django 4.0 on 2023-01-20 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_allproducts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproducts',
            name='miqdor_birligi',
            field=models.CharField(help_text="O'lchov birligini kiriting: Kg, Tonna, Vagon, Litr, Dona", max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='photo',
            field=models.ImageField(default='images/no-image.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='soldproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldproducts', to='products.allproducts'),
        ),
    ]
