# Generated by Django 4.0 on 2023-01-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_allproducts_miqdor_birligi_alter_allproducts_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allproducts',
            name='narxi',
        ),
        migrations.AddField(
            model_name='allproducts',
            name='birlik_narxi',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='allproducts',
            name='umumiy_narxi',
            field=models.FloatField(null=True),
        ),
    ]
