# Generated by Django 4.0 on 2023-01-20 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_allproducts_narxi_allproducts_birlik_narxi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allproducts',
            name='umumiy_narxi',
        ),
    ]
