# Generated by Django 4.0 on 2023-01-20 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_allproducts_umumiy_narxi'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproducts',
            name='miqdori',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
