# Generated by Django 4.0 on 2023-01-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_soldproducts_miqdori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldproducts',
            name='miqdori',
            field=models.PositiveIntegerField(help_text='Sotilgan mahsulot miqdorini kiriting.', null=True),
        ),
    ]
