# Generated by Django 4.0 on 2023-01-21 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_soldproducts_miqdori'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproducts',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
